# Generated by Django 4.0.4 on 2022-06-09 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='main',
            old_name='updated_date',
            new_name='updated',
        ),
    ]
