# Generated by Django 4.0.4 on 2022-06-16 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_main_price_drop_color_alter_main_price_drop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='main',
            name='price_drop_color',
        ),
    ]
