# Generated by Django 4.0.4 on 2022-06-16 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_main_current_price_alter_main_previous_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='main',
            name='price_drop',
        ),
        migrations.AddField(
            model_name='main',
            name='price_change',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='main',
            name='current_price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='main',
            name='previous_price',
            field=models.FloatField(default=0.0),
        ),
    ]
