# Generated by Django 4.0.4 on 2022-06-16 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_main_price_drop_main_price_change_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main',
            name='current_price',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='main',
            name='previous_price',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
